name: .NET Build Dirty

on:
  push:
    branches: [ dirty ]
  pull_request:
    branches: [ dirty ]
    types: [synchronize]

jobs:
  dirty:
    name: Build Dirty Docker if Dirty push
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/dirty' }}
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3
        with:
          ref: dirty

      - name: NodeJS to Compile WebUI
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: |
          cd UI/Web || exit
          echo 'Installing web dependencies'
          npm install --legacy-peer-deps

          echo 'Building UI'
          npm run prod

          echo 'Copying back to Kavita wwwroot'
          rsync -a dist/ ../../API/wwwroot/

          cd ../ || exit

      - name: Compile dotnet app
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: 7.0.x

      - name: Install Swashbuckle CLI
        run: dotnet tool install -g --version 6.5.0 Swashbuckle.AspNetCore.Cli

      - run: ./monorepo-build.sh

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: ghcr.io/bakeneko/kavita:dirty

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
